DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS professors;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS teacher_to_course;
DROP TABLE IF EXISTS student_to_course;
DROP TABLE IF EXISTS tests;
CREATE TABLE students (student_id INT (10) PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE, username VARCHAR (50) NOT NULL, password VARCHAR (200) NOT NULL, fname VARCHAR (25) NOT NULL, lname VARCHAR (25) NOT NULL, email VARCHAR (50) NOT NULL, phonenum VARCHAR (14) NOT NULL);
CREATE TABLE professors (professor_id INT (10) PRIMARY KEY NOT NULL UNIQUE, username VARCHAR (50) NOT NULL, password VARCHAR (200) NOT NULL, fname VARCHAR (25) NOT NULL, lname VARCHAR (25) NOT NULL, email VARCHAR (50) NOT NULL, phone VARCHAR (14) NOT NULL);
CREATE TABLE courses (course_id INT (10) PRIMARY KEY NOT NULL, name VARCHAR (100) NOT NULL, description VARCHAR (250) NOT NULL);
CREATE TABLE teacher_to_course (professor_id INT NOT NULL, course_id INT NOT NULL);
CREATE TABLE student_to_course (student_takes_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE, student_id INT NOT NULL, course_id INT NOT NULL);
CREATE TABLE tests (student_takes_id INT PRIMARY KEY NOT NULL, test_1 INT (3), homework_1 INT (3));
ALTER TABLE teacher_to_course ADD CONSTRAINT teacher_to_course_professor_idprofessors_professor_id FOREIGN KEY (professor_id) REFERENCES professors(professor_id);
ALTER TABLE teacher_to_course ADD CONSTRAINT teacher_to_course_course_idcourses_course_id FOREIGN KEY (course_id) REFERENCES courses(course_id);
ALTER TABLE student_to_course ADD CONSTRAINT student_to_course_student_idstudents_student_id FOREIGN KEY (student_id) REFERENCES students(student_id);
ALTER TABLE student_to_course ADD CONSTRAINT student_to_course_course_idcourses_course_id FOREIGN KEY (course_id) REFERENCES courses(course_id);
ALTER TABLE tests ADD CONSTRAINT tests_student_takes_idstudent_to_course_student_takes_id FOREIGN KEY (student_takes_id) REFERENCES student_to_course(student_takes_id);
